layout:
  - experiences
  - educations
  - skills
  - certificates
  - awards

experiences:
  - company: Superbank
    location: Jakarta Selatan
    role: Technical Support
    dates: December 2024 - June 2025
    job_type: Internship
    points:
      - "**Managed end-to-end deployment** of vendor-provided scripts across **AWS EC2** (Dev/Staging) via **S3 bucket integration**, **WinSCP** file transfers, and **XML configuration adjustments**."
      - "**Automated deployment workflows** by developing a **PowerShell script** to extract ZIP files and **configuration for deployment processes**, **reducing manual effort by 40%** and accelerating deployment cycles."
      - "**Resolved production incidents** (e.g., CPU spikes, SQL query bottlenecks) by acting as a technical liaison, **analyzing root causes**, and **escalating issues** via **Jira tickets** to cross-functional teams."

  - company: PT XL Axiata Tbk
    location: Jakarta Selatan
    role: "Fixed Connectivity, ICT & Cloud"
    dates: February 2024 - June 2024
    job_type: Internship
    points:
      - "Conducted **comprehensive market research** and **data scraping** using **Python**, **BeautifulSoup**, and **Pandas** to identify **growth opportunities** and assess the competitive landscape for satellite products."
      - "Presented **data-driven findings** and **strategic recommendations** to mentors and senior management to support **informed business strategy** and **product development**."
      - "Collaborated closely with **cross-functional teams** to ensure timely completion of tasks and seamless **integration of research insights** into project outcomes."

  - company: PT Bank Victoria International
    location: Jakarta Selatan
    role: Fullstack Web Developer
    dates: September 2023 - November 2023
    job_type: Internship
    points:
      - "Developed **dynamic journal booking tables** on the frontend with **Flutter**, integrating advanced **filtering** (by date and booking type), **pagination**, and **soft deletion** functionalities."
      - "**Integrated the Flutter frontend with backend APIs built in NestJS** and maintained data consistency with **MySQL**, ensuring accurate real-time accounting records."
      - "Executed **targeted database queries** to correct and optimize data integrity, working in close collaboration with teams to align front-end displays with updated backend data."

  - company: MileApp
    location: Jakarta Barat
    role: Frontend Web Developer
    dates: September 2022 - October 2022
    job_type: Internship
    points:
      - "**Rebuilt and redesigned** critical web pages (**landing, login, and registration**) from scratch using **React** and **styled-components**, contributing to a major UI overhaul aimed at **improving user experience and performance** for field agents and administrators."
      - "Collaborated remotely with supervisors to integrate the new **React-based frontend** with the platform’s evolving product direction, **replacing legacy code with scalable, maintainable components**."

projects:
  - name: DanceRTOS
    github: https://github.com/cattyman919/AbsenceSystem
    github_handle: cattyman919/AbsenceSystem
    description: "An attendance system using FreeRTOS ESP32 and RFID, with a web server and Blynk integration for class and schedule management."
    points:
      - "Led the end-to-end development of the DanceRTOS attendance system, building both the **Flutter frontend** and **NestJS backend**."
      - "Engineered a real-time student login system using **MQTT** and **RFID** on an **ESP32**, enabling secure and instantaneous attendance tracking."
      - "Designed and implemented a dynamic class schedule and attendance table, providing lecturers with an organized and **real-time view of student presence**."

  - name: Electronic Vault Lock
    github: https://github.com/rroiii/Electronic-Vault-Lock
    github_handle: rroiii/Electronic-Vault-Lock
    description: "A secure 4-digit combination lock for protecting items, offering a simple and reliable locking mechanism."
    points:
      - "Authored and optimized the **VHDL code** for the electronic vault lock, ensuring robust and reliable security."
      - "Conducted extensive simulations in **ModelSim** to validate the system's performance and identify potential vulnerabilities."
      - "Led the synthesis of the design in **Quartus**, optimizing for area and power to create an efficient and compact solution."

  - name: VAIO (Vacuum All in One)
    github: https://github.com/VAIO-CE/VAIO-Code
    github_handle: VAIO-CE/VAIO-Code
    description: "VAIO is an ESP32-based robot featuring autonomous navigation, a vacuum system, and multiple intuitive control methods including a sensor-equipped glove, voice commands via speech recognition, and a standard PS4 controller."
    points:
      - "Architected a modular and scalable codebase in **C++** on the **PlatformIO IDE**, enabling efficient team collaboration and future development."
      - "Engineered a real-time gyroscope-based control system with **ESP-NOW**, allowing for intuitive and responsive robot control via a wearable glove."
      - "Implemented a multi-threaded **FreeRTOS** environment to manage concurrent tasks, ensuring seamless switching between autonomous, gesture, and PS4 control modes."
